#!/usr/bin/env bash
# One-shot VPS setup for fleet-hub + fleet-mcp.
#
# Prereqs: Ubuntu/Debian, sudo, git, git clone of this repo at
#   /opt/opencli_agent/.  Run as your normal (non-root) user with sudo rights.
#
# Usage:
#   sudo ./deploy/vps/setup.sh <PUBLIC_IP> [<REPO_URL>]
#
# Example:
#   sudo ./deploy/vps/setup.sh 34.46.31.68 https://github.com/you/opencli_agent.git
#
# After this runs, fleet-hub is on systemd and Caddy exposes only /health plus
# the agent WebSocket endpoint publicly. REST and the token-bearing installer
# endpoint stay localhost-only on the VPS.

set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
    echo "Must run as root (use sudo)." >&2
    exit 1
fi

if [ -z "${SUDO_USER:-}" ]; then
    echo "Expected to be run via 'sudo ./setup.sh ...', not as root directly." >&2
    exit 1
fi

PUBLIC_IP="${1:-}"
REPO_URL="${2:-https://github.com/YOUR_ORG/opencli_agent.git}"
OWNER_USER="$SUDO_USER"
OWNER_HOME=$(getent passwd "$OWNER_USER" | cut -d: -f6)
ROOT=/opt/opencli_agent

if [ -z "$PUBLIC_IP" ]; then
    echo "usage: sudo $0 <PUBLIC_IP> [REPO_URL]" >&2
    exit 2
fi

PUBLIC_HOST="${PUBLIC_IP}.sslip.io"

echo "==> Install OS packages"
apt-get update -q
apt-get install -y -q python3 python3-venv python3-pip curl git debian-keyring debian-archive-keyring apt-transport-https

echo "==> Install Caddy (if missing)"
if ! command -v caddy >/dev/null 2>&1; then
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
        | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
        > /etc/apt/sources.list.d/caddy-stable.list
    apt-get update -q
    apt-get install -y -q caddy
fi

echo "==> Install uv (as $OWNER_USER)"
sudo -u "$OWNER_USER" bash -c "curl -LsSf https://astral.sh/uv/install.sh | sh"
UV="$OWNER_HOME/.local/bin/uv"

echo "==> Ensure $ROOT exists and owned by $OWNER_USER"
install -d -o "$OWNER_USER" -g "$OWNER_USER" "$ROOT"

if [ ! -d "$ROOT/.git" ]; then
    echo "==> Cloning $REPO_URL into $ROOT"
    sudo -u "$OWNER_USER" git clone "$REPO_URL" "$ROOT"
else
    echo "==> Repo already at $ROOT (skipping clone)"
fi

echo "==> Build fleet-hub venv"
sudo -u "$OWNER_USER" bash -c "cd $ROOT/fleet-hub && $UV venv .venv && $UV pip install -e ."

echo "==> Build fleet-mcp venv"
sudo -u "$OWNER_USER" bash -c "cd $ROOT/fleet-mcp && $UV venv .venv && $UV pip install -e ."

echo "==> Write fleet-hub .env"
HUB_ENV="$ROOT/fleet-hub/.env"
cat > "$HUB_ENV" <<EOF
# Generated by deploy/vps/setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
HOST=127.0.0.1
PORT=8031

DATABASE_URL=sqlite+aiosqlite:///$ROOT/fleet-hub/fleet_hub.db
NODE_TOKEN_BYTES=32
AUDIT_LOG_PATH=$OWNER_HOME/.fleet-hub/audit.log

DEFAULT_TASK_TIMEOUT_SEC=120
MAX_TASK_TIMEOUT_SEC=600
WS_PING_INTERVAL_SEC=30
WS_PING_TIMEOUT_SEC=10
NODE_OFFLINE_AFTER_SEC=60

PUBLIC_URL=https://${PUBLIC_HOST}
OPENCLI_NPM_SPEC=@jackwener/opencli@latest
FLEET_AGENT_INSTALL_SPEC=git+${REPO_URL}#subdirectory=fleet-agent

LOG_LEVEL=INFO
EOF
chown "$OWNER_USER:$OWNER_USER" "$HUB_ENV"
chmod 640 "$HUB_ENV"

echo "==> Write fleet-mcp .env"
MCP_ENV="$ROOT/fleet-mcp/.env"
cat > "$MCP_ENV" <<EOF
HUB_URL=http://localhost:8031
RATE_LIMIT_PER_NODE=10
RATE_LIMIT_GLOBAL=60
AUDIT_LOG_PATH=$OWNER_HOME/.fleet-mcp/audit.log
MAX_ITEMS_INLINE=50
TASK_TIMEOUT_SEC=120
BROADCAST_TIMEOUT_SEC=180
LOG_LEVEL=INFO
EOF
chown "$OWNER_USER:$OWNER_USER" "$MCP_ENV"
chmod 640 "$MCP_ENV"

echo "==> Install systemd unit"
sed "s/__USER__/$OWNER_USER/g" "$ROOT/deploy/vps/fleet-hub.service" \
    > /etc/systemd/system/fleet-hub.service
install -d -o "$OWNER_USER" -g "$OWNER_USER" "$OWNER_HOME/.fleet-hub"
systemctl daemon-reload
systemctl enable --now fleet-hub.service

echo "==> Install Caddyfile"
sed "s/__PUBLIC_HOST__/$PUBLIC_HOST/g" "$ROOT/deploy/vps/Caddyfile" > /etc/caddy/Caddyfile
systemctl reload caddy

echo "==> Wait for hub to respond"
for i in $(seq 1 30); do
    if curl -fsS http://localhost:8031/health >/dev/null 2>&1; then
        break
    fi
    sleep 1
done

if curl -fsS http://localhost:8031/health >/dev/null 2>&1; then
    echo "==> fleet-hub OK on localhost"
else
    echo "!! fleet-hub not responding on localhost — check: journalctl -u fleet-hub -f" >&2
    exit 3
fi

echo
echo "=================================================================="
echo "Done."
echo
echo "Public URL:   https://${PUBLIC_HOST}"
echo "Test:         curl https://${PUBLIC_HOST}/health"
echo "              (may take 30-60s for Caddy to get Let's Encrypt cert)"
echo
echo "Firewall: make sure ports 80 and 443 are open to the world."
echo
echo "Next — register a node, then install on the laptop:"
echo "  curl -X POST http://localhost:8031/api/v1/nodes \\"
echo "    -H 'content-type: application/json' \\"
echo "    -d '{\"label\":\"home-wsl\"}'"
echo
echo "Then on laptop (WSL2 / macOS / Linux):"
echo "  ssh ${OWNER_USER}@${PUBLIC_IP} \\"
echo "    'curl -s http://localhost:8031/api/v1/nodes/install/agent.sh?label=home-wsl' \\"
echo "    | bash"
echo "=================================================================="
